name: my workflow
on: push
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint
      - name: test code
        run: npm run test
      - name: build code
        run: npm run build